stages:
  - test

.rawhide:
  tags:
    - rawhide
    - libvirt
  before_script:
    - >
      sudo dnf -y -q  install
      autoconf automake device-mapper-devel gcc gettext-devel json-c-devel
      libargon2-devel libblkid-devel libpwquality-devel libselinux-devel
      libssh-devel libtool libuuid-devel make openssl-devel popt-devel
      libsepol-devel.x86_64 netcat openssh-clients passwd pkgconfig sharutils
      sshpass tar uuid-devel vim-common device-mapper expect gettext git jq
      keyutils
    - sudo -E git clean -xdf
    - ./autogen.sh
    - ./configure --enable-fips --enable-pwquality --enable-libargon2 --enable-selinux

test-mergerq-job-rawhide:
  extends: .rawhide
  stage: test
  interruptible: true
  variables:
    RUN_SSH_PLUGIN_TEST: "1"
  rules:
    - if: $CI_PROJECT_PATH != "oniko/cryptsetup"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - make -j
    - make -j -C tests check-programs
    - sudo -E make check
    - sudo -E make clean

test-main-commit-job-rawhide:
  extends: .rawhide
  stage: test
  interruptible: true
  variables:
    RUN_SSH_PLUGIN_TEST: "1"
  rules:
    - if: $CI_PROJECT_PATH != "oniko/cryptsetup"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - make -j
    - make -j -C tests check-programs
    - sudo -E make check
    - sudo -E make clean
