#!/bin/bash

[ -z "$CRYPTSETUP_TESTS_BIN_PATH" ] && CRYPTSETUP_TESTS_BIN_PATH="."
[ -z "$LIBCRYPTSETUP_DIR" ] && LIBCRYPTSETUP_DIR=../.libs
FILE=$LIBCRYPTSETUP_DIR/libcryptsetup.so

fail()
{
	[ -n "$1" ] && echo "$1"
	exit 2
}

skip()
{
	[ -n "$1" ] && echo "$1"
	exit 77
}

test -d $LIBCRYPTSETUP_DIR || fail "Directory $LIBCRYPTSETUP_DIR is missing."
test -f $FILE || skip "WARNING: Shared $FILE is missing, test skipped."

$CRYPTSETUP_TESTS_BIN_PATH/all-symbols-test $FILE $@
