#!/bin/bash

[ -z "$LIBCRYPTSETUP_DIR" ] && LIBCRYPTSETUP_DIR=../.libs
FILE=$LIBCRYPTSETUP_DIR/libcryptsetup.so

function fail()
{
	[ -n "$1" ] && echo "$1"
	exit 2
}

function skip()
{
	[ -n "$1" ] && echo "$1"
	exit 77
}

test -d $LIBCRYPTSETUP_DIR || fail "Directory $LIBCRYPTSETUP_DIR is missing."
test -f $FILE || skip "WARNING: Shared $FILE is missing, test skipped."

./all-symbols-test $FILE $@
