#!/usr/bin/expect -f

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}


set program [lindex $argv 0]
set arguments [lrange $argv 1 end]

set timeout -1

spawn $program {*}$arguments

match_max 100000
expect "The new key will temporarily be stored in /run/user/"
send -- "\r"
expect "Enter passphrase:"
send -- "PASSPHRASE\r"
expect eof
