test-gcc-compilation:
  extends:
    - .gitlab-shared-docker
  script:
    - export CFLAGS="-Wall -Werror"
    - ./configure --enable-cryptsetup-reencrypt --enable-pwquality --enable-libargon2 || cat config.log
    - make -j

test-gcc-Wall-script:
  extends:
    - .gitlab-shared-docker
  script:
    - export CC=".gitlab/ci/gcc-Wall"
    - ./configure --enable-cryptsetup-reencrypt --enable-pwquality --enable-libargon2 || cat config.log
    - export CFLAGS="-g -O0 -Werror"
    - make -j

test-gcc-fanalyzer:
  extends:
    - .gitlab-shared-docker
  script:
    - export CFLAGS="-Wall -Werror -fanalyzer"
    - ./configure --enable-cryptsetup-reencrypt --enable-pwquality --enable-libargon2 || cat config.log
    - make -j
